### ISSUE TITLE
[BUG] Missing and not working right click 'Force.com' right click context menu from Editor

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#109]
Please bring back the Right click (Shift + F10) context menu when in the Editor, I had a system macro that would auto navigate to the Save to Server and bypass the prompts, now the menu has been removed I can not use the latest salesforce.com Beta.

You can still right click in on the file in the 'Project Explorer' view but it's not working, it just does a Synchronize but never saves to server. 

Both builders are enabled.

**Comment by danielsokolowski** [comment]
I still keep my 'Default Builder' disabled because during GIT pulls it triggers a file change and push to the server automatically, so I was always using the 'Save to Server' option.

**Comment by danielsokolowski** [comment]
Anyone looking for the older version, they can be found here: http://media.developerforce.com/force-ide/eclipse42

Perhaps could we please add this information to this page just in people need to revert? : https://github.com/forcedotcom/idecore/wiki/Downloading-the-Beta-Version-of-the-Force.com-IDE

**Comment by vazexqi** [comment]
@danielsokolowski - What are you using to invoke your system macro? This is not essential for the bug but I'm just curious to get a better understanding of your use case.

**Comment by danielsokolowski** [comment]
I use 'TyperTask' - see answer here: http://salesforce.stackexchange.com/questions/9278/force-com-ide-easy-push-of-single-file-through-single-key-combo

**Comment by danielsokolowski** [comment]
Just wanted to updated that based on your comment in the #108 issue I have downgraded to Juno, I was able to see the Force.com context menu only once, the moment I disabled the Onlline builder it disappeared, enabling it didn't bring it back. I am still able to see the Save to Server when clicking in the Project Explorer folder view.

I will downgrade to v33 and see if I run into any issues.

**Comment by vazexqi** [comment]
![screen shot 2015-05-13 at 6 51 37 pm](https://cloud.githubusercontent.com/assets/54414/7624701/e8e6898e-f9a1-11e4-958a-4b0115fc4b90.png)

@danielsokolowski 
Should be addressed in 4e2970db133521fce387fcbdc55a47822434f9cf and 002eeec8ae18711198e78c53f5445e68c6fb36c6. Doing testing first before pushing to beta but should be out soon.

We intentionally removed it because during the streamlining of the entire command handling inside Eclipse – all credits go to external contributor fdutton . As part of that refactoring, we removed it from the editor. For more info, see #96.

However, I can see why some people might prefer it so I'm adding it back.

**Comment by vazexqi** [comment]
@danielsokolowski This has been fixed in the latest beta.
