### ISSUE TITLE
Package Manifest content warning

### ISSUE THREAD

**Issue by prolayc** [forcedotcom/idecore#111]
Hello idecore Team,

I am using Eclipse Juno 4.2 and Java 1.8 for force.com Eclipse plugin. I tried installing Eclipse plugin couple of times but always getting the following warnings as mentioned in the image. 

My question is that why Eclipse plugin is always saying these components are not supported. Please find the picture below.

![force com-ide-error](https://cloud.githubusercontent.com/assets/5306583/7785531/6eb25fae-01b1-11e5-89b9-6b334d13a8c5.PNG)
![force com-ide-error](https://cloud.githubusercontent.com/assets/5306583/7785533/8ed53d9c-01b1-11e5-8ed0-c3ac8181e2fb.PNG)
Thanks,
Prolay

**Comment by vazexqi** [comment]
@prolayc. Short answer. That's working as designed. We don't support all the metadata types available in the Metadata API. So that alert is just informing you what we don't support. 

Longer answer. We are moving toward making the IDE more programmatic-focused, i.e., for editing code and not retrieve/deploy metadata. 

If you need that then the Force.com Ant Migration Tool might fulfill your needs better. 

However, feel free to make a pull request to add support for those metadata types.

**Comment by prolayc** [comment]
Thank you @vazexqi
