### ISSUE TITLE
No Run Tests menu item after upgrading to v.34

### ISSUE THREAD

**Issue by andrew-chiz-muzychuk** [forcedotcom/idecore#115]
Just upgraded from 33 to 34 on my Eclipse Luna. Now Run Tests menu item is missing from Force.com menu.

**Comment by vazexqi** [comment]
@andrew-chiz-muzychuk: The method to run tests have changed. Could you take a look at https://github.com/forcedotcom/idecore/wiki/Changes-in-Force.com-IDE-Beta-Version-34.0.0.20150511 

We plan to add a right-click menu back like the Java tools that would be a shortcut to the steps above. But use those steps for now.

**Comment by andrew-chiz-muzychuk** [comment]
@vazexqi, thank you for your explanation.
I'm just curious, why this shortcut was removed? As for me, I used it a lot and it's strange for me to remove such a useful option.

**Comment by vazexqi** [comment]
@andrew-chiz-muzychuk It was removed because the implementation changed. We just need to re-wire it up again. With the new implementation there are a few more steps but shouldn't be too involved:  see what was right-clicked, determine if it is a test, create a test configuration (if one doesn't already exist), launch it.

If you would like, I can point you to the right place and you can take a stab at the code :-)

**Comment by andrew-chiz-muzychuk** [comment]
@vazexqi, thanks, but I haven't done this before, so it will take a lot of time to understand, how to do it and implement.
