### ISSUE TITLE
Unable to create project

### ISSUE THREAD

**Issue by GradyD** [forcedotcom/idecore#117]
I installed the beta version and when I try to create a Force.com project I get the following error.

"Building workspace has encountered a problem. Errors occurred during the build."

Detailed error
```
Errors occurred during the build.
Errors running builder 'Force.com Default Builder' on project 'Test prod 3'.
Class com.salesforce.ide.core.compatibility.auth.equinox.EquinoxAuthorization does not implement the requested interface com.salesforce.ide.core.compatibility.auth.IAuthorizationService
```

**Comment by vazexqi** [comment]
@GradyD Hmmm, I'm not sure how that would be possible since that would mean that the product won't even build with a compile error. See https://github.com/forcedotcom/idecore/blob/master/com.salesforce.ide.core.compatibility.auth.equinox/src/com/salesforce/ide/core/compatibility/auth/equinox/EquinoxAuthorization.java and the interface class itself at https://github.com/forcedotcom/idecore/blob/master/com.salesforce.ide.core.compatibility/src/com/salesforce/ide/core/compatibility/auth/IAuthorizationService.java

1. Which version of Eclipse did you install this into?
1. What version of Java are you using?
1. What other plug-ins do you have?

Could you try installing into a fresh instance of Eclipse and see if the problem persists?

**Comment by GradyD** [comment]
Just tried with a fresh install and it seems to be doing much better. Must have been something funky with my previous install. 

Thanks for the quick response
