### ISSUE TITLE
Why is the IDE so slow when the Tooling API is so fast?

### ISSUE THREAD

**Issue by GradyD** [forcedotcom/idecore#118]
It takes right at 5 minutes for me to download Apex and Visualforce from our production org. I can do the same thing in under a minute using MavensMate. 

Why is this? Is the IDE not using the tooling API yet?

For the record MavensMate is a good plugin but I prefer to use officially support SF tools.

**Comment by danielsokolowski** [comment]
I can't comment on the initial project download but the Force.com ide is starting to use the tooling API and normal editing is very acceptable to me.

**Comment by GradyD** [comment]
Once everything is downloaded it seems to do good its just the initial download/push of the data that seems slow.

**Comment by danielsokolowski** [comment]
I would also check the actuall default files that are download with MavensMate and Force.com IDE - I know Force.com IDE downloads referenced package source code as well. You should get the latest version (stable) release it has a status window, older releases you had no idea how long things would take.

**Comment by GradyD** [comment]
My status window is there but it locks up and finishes right at 5 minutes later.

**Comment by vazexqi** [comment]
@GradyD It's an issue with the Eclipse API we are using to store the metadata from the initial retrieve.

For the initial retrieve, we do it through Metadata API using the [`retrieve()`](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_retrieve.htm) call. Once this completes, we persist a series of metadata from [`RetrieveResult`](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_retrieveresult.htm#meta_retrieveresult), e.g., createdById, createdByName, etc.

It's slow because we are storing it into Eclipse's internal database for each file. See attached yourkit profile and also IResource.setPersistentProperty(). As far as I can tell, there is no bulk setPersistent*Properties* API.

<img width="2034" alt="profile_eclipse" src="https://cloud.githubusercontent.com/assets/54414/8641556/58fb6dee-28cc-11e5-94f5-48376ce39912.png">

I don't (yet) have a good solution to this that doesn't involve a major refactoring of how we store the metadata. We have tried to alleviate the issue by doing this in a background thread but the metadata is essential for the IDE. For instance, if you don't have the ID of the resource ready, you can't use the Tooling API to perform any updates since Tooling API operates via IDs. 

I suspect MavensMate doesn't run into this issue because they have a different indexing system that they use for storing the metadata – perhaps directly into a (hidden) companion file.

**Comment by GradyD** [comment]
This makes sense. 

Thank you

**Comment by GradyD** [comment]
I just wanted to let everyone know that I updated my eclipse to Mars this morning and the download of the meta data is MUCH faster! I was shocked.

**Comment by gwickman** [comment]
I've been running Force.com IDE on Juno and stopped using Eclipse on my current project because it's 
2.5k apex modules with 8m characters of apex and even with 2Gb memory allocated Eclipse couldn't cope.
Tried a dodgy upgrade by putting Mars in the upgrade path and upgrading Juno and that plus the Beta force.com IDE it actually feels a bit faster than Sublime now. So well done.

**Comment by ram4ufriends** [comment]
GradyD, gwickman - What's the IDE plug-in version you are using?

**Comment by GradyD** [comment]
I was using the latest production release. 

gwickman says he is using the beta release.

**Comment by gwickman** [comment]
ram im using Beta-Version-34.0.0.20150511

**Comment by ram4ufriends** [comment]
Thanks GradyD and gwickman. Just curious, auto complete works only in beta plug-in as of now right?

**Comment by ram4ufriends** [comment]
Just to echoing that Eclipse Mars download is faster. Also, just noticed that if you have project setup as Build Automatically, save is so much faster rather than using Force.com -> Save to server option. I am sure many of you might know this, but just wanted to post if it helps anybody.

**Comment by GradyD** [comment]
@ram4ufriends can you point me to the docs on that or tell me what it does and how to enable it?

Thanks

**Comment by ram4ufriends** [comment]
In Eclipse Project Select Build Automatically. This saves in under 5 seconds where as Save to Server  option took 3 minutes to save a file.

**Comment by GradyD** [comment]
I assume that this auto saves changes to the server?

**Comment by ram4ufriends** [comment]
Yes it does. Not sure why this option saves to server, but I validated in server as well. Under 5 seconds(Build Automatically option) vs couple of minutes(Save to Server option) is a big deal.

**Comment by GradyD** [comment]
:+1:

**Comment by ram4ufriends** [comment]
Let me know if it works

**Comment by danielsokolowski** [comment]
Having the 'Work Online' or 'Build Automatically' has side effects when 
you also are using a repository to track your source change - doing a 
'Pull' triggers an update which seems to want to save to server which 
might not be desired if the repo was outdated.

On 7/31/2015 12:41 PM, ram4ufriends wrote:
>
> Just to echoing that Eclipse Mars download is faster. Also, just 
> noticed that if you have project setup as Build Automatically, save is 
> so much faster rather than using Force.com -> Save to server option. I 
> am sure many of you might know this, but just wanted to post if it 
> helps anybody.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/forcedotcom/idecore/issues/118#issuecomment-126747633>.
>
>

-- 
Daniel Sokolowski
Danols Web Engineering
http://webdesign.danols.com/
Office: 613-817-6833
Fax: 613-817-5340
Toll Free: 1-855-5DANOLS
Kingston, ON K7L 1H3, Canada


Notice of Confidentiality:
The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review re-transmission dissemination or other use of or taking of any action in reliance upon this information by persons or entities other than the intended recipient is prohibited. If you received this in error please contact the sender immediately by return electronic transmission and then immediately delete this transmission including all attachments without copying distributing or disclosing same.

**Comment by ceiroa** [comment]
Is there a setting to make sure the Force.com IDE is using the Tooling API and not the Metadata API when saving changes to files while working in online mode?
