### ISSUE TITLE
[BUG?] 'Deploy to Server' triggers Synchronize with server

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#121]
Even when Eclipse builders are off, or Force.com plugin is in offline mode choosing to 'Deploy to Server' triggers a Synchronize with server, this might be problematic if I am wanting to push specific version of my files which are version controlled.

**Comment by vazexqi** [comment]
Could you elaborate on why this is a problem? Some people seem to like this option because it prevents them from overwriting new code on the server. So it does a synchronize to be sure.

On the other side of the fence, we have heard complains that the default behavior (using Ctrl + S) which does a quick save (and doesn't synchronize) is not ideal for team development. See Issue #66
