### ISSUE TITLE
Work offline still try connect to salesforce

### ISSUE THREAD

**Issue by maroscassa** [forcedotcom/idecore#152]
Hi, is it possible to fix the issue when I set to project Work Offline to not connect into salesforce? For example:
I have project of sandbox in my eclispe. I want to refresh sandbox, so I will make backup and set the project to work offline. Then I will make refresh and create new project in eclipse. I want to let old project in eclipse for backup for some reason. But now, when I want to open file from old project it throw error about incorrect credentials. It's attempt to login into salesforce, and I was sometimes kicked from salesforce security for too many attempts with wrong password. I do not want change this security, I just do not want to eclipse try to connect into salesforce when project is 'Work Offline'.

Thank you.

**Comment by vazexqi** [comment]
@maroscassa. There are some functionality that do require connection to Salesforce. For instance, to fetch the data for system completions. Or to create a new Trigger, we need to know what kind of objects (including new custom objects) that you have.

Could you share what your use cases are for being fully offline? That might help us drill down to the gist of the issue here. Thanks!

**Comment by maroscassa** [comment]
I understand that if you are offline, that you can download newer version of metadata. But In my case I just want to open file - for example Class, or object definition. So I think, that in this case, it should not try to connect into SFDC. It should connect into SFDC, only when I click on Refresh From Server, or Save to Server.
