### ISSUE TITLE
Sanity Check: Contributing to project setup steps errors out

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#164]
Could someone just do a sanity check for me, I was able to set the development up many moon ago as per https://github.com/forcedotcom/idecore/wiki/Getting-Started 

Trying to set it up again from 'master' branch (as of today) I am only getting following projects importeed. Could someone check on their on if they have no issues following those instructions (wonder if my Eclipse installation is at issue):

'''
com.salesforce.ide.apex.core
com.salesforce.ide.apex.core.test
com.salesforce.ide.core.test
com.salesforce.ide.deployment.test
com.salesforce.ide.test
com.salesforce.ide.test.commonlibs
com.salesforce.ide.ui.editors.test
com.salesforce.ide.ui.test
com.salesforce.ide.upgrade.test
'''

When I open the ForceIDE_Eclipse45.target it errors out with ""An internal error occurred during: "Resolving Target Definition". java.lang.NullPointerException"

**Comment by vazexqi** [comment]
@danielsokolowski Are you using Java 8 and Eclipse Mars 4.5 RCP/RAP?
I just made that change a few days ago and so far our internal teams have been able to set them up.
Could you provide more details on which target it is hitting the NullPointerException on?

**Comment by danielsokolowski** [comment]
It was an improperly synced up local working tree with the current master, by following the instructions and installing a clean eclipse and doing a fresh clone it does work.

However, would you know how I can increase Eclipse's Error log details? - sorry for the newb question by my search came up short.

When I try to the target org setup with my existing Eclipse workspace (that has the  Eclipse PDE Plug-in Developer Resources 3.11.1.v20150904-0345) it chokes with a "Invalid byte 1 of 1-byte UTF-8 sequence." error but I can not track which file.

![image](https://cloud.githubusercontent.com/assets/273413/12953215/6ba42310-cfe7-11e5-8720-00a635d6ef60.png)

**Comment by vazexqi** [comment]
Hmmm, this one is harder to debug since it's in actual Eclipse instance that you're running in. I can't think of a way to debug this one easily.

You could try using the tips in the "Debug Mode" [section](https://www.eclipse.org/eclipse/platform-core/documents/3.1/debug.html) to increase the logging for org.eclipse.pde plug-in.

Off the top of my head, based on the stacktrace, it looks like it might be having trouble fetching something from the network. You could install a network proxy like [Charles](https://www.charlesproxy.com/) (not endorsing it, just first one to come to mind) and monitor to see if the data coming in is malformed in some way.

What else could you tell me about the workspace/Eclipse instance where this failed? Is it on Mars 4.5 RCP/RAP?

**Comment by danielsokolowski** [comment]
I've added the debug/tracing options with no additional info.

The Eclipse IDE I use is the Runtime Platform Binary (http://download.eclipse.org/eclipse/downloads/drops4/R-4.5.1-201509040015/#PlatformRuntime) with my own install script of all various plugins (https://bitbucket.org/danielsokolowski/eclipse-install-default-plugins/src/ba557ecc0a277a8b07910fd9f13fb6ad914fdd4f/install-default-plugins-for-4.5.x-simplified.bat?at=default&fileviewer=file-view-default) - nothing too fancy.

The clean/fresh install works, so let's leave this mystery for another time when I will try the capturing traffic.

**Comment by vazexqi** [comment]
@danielsokolowski - I'm going to close this now since it seems that it might be a configuration issue somewhere. It seems you are not blocked by using a clean/fresh install.

If you are planning to add a feature/fix a bug, let me know if you need help with any other aspects.
