### ISSUE TITLE
Apex Test Run configuration "all methods" is not running "all methods"

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/idecore#166]
When you setup a run configuration to execute Apex Tests, you can choose the specific Apex Class that contains the Unit tests.  If the test class has test methods AAA, BBB, CCC, and DDD, you can choose "all methods".  Based on what I am seeing in the "Launch configuration" file, that is not correct.  It appears that "testsArray" attribute gets loaded with each of the test names instead of the some value that represents the implied behavior of "all methods".

The behavior is probably not desired.  I have spent the past half hour trying to figure out why it was that my test methods EEE, FFF, GGG, and HHH (that were added after I created the run configuration) were not executing.  The issue was simply that the Launch configuration file "testsArray" attribute was not getting updated as I added new methods.  The workaround was that I have to edit the run configuration each time that I add a new test method.

I suspect that the majority for ForceDotCom IDE users will not pickup on this subtle behavior and they will only conclude that the IDE is not working.

I would suggest changing the behavior of the run configuration, to store a "testsArray" attribute value of "all methods" (or something to that effect) and then when the run configuration is launched, have it dynamically scan the test class in question to determine all of the test methods that are present in that class so that the launcher can call the appropriate test methods via the ToolingAPI.

I hope this helps.

Cheers!

BTW - Love the code lines that are covered being highlighted after the test execution!

**Comment by vazexqi** [comment]
@ImJohnMDaniel - Thanks for the detailed feedback – really appreciate it. Agreed. We'll get a fix in.

**Comment by ImJohnMDaniel** [comment]
Glad to help!

**Comment by vazexqi** [comment]
See https://vimeo.com/157502613. Should be pushed soon to the beta channel.

**Comment by ImJohnMDaniel** [comment]
Vimeo video looks great. I appreciate the help. Cheers!!!!

**Comment by vazexqi** [comment]
@ImJohnMDaniel - I also want to be clear that we don't have an (all classes) option that can handle addition/deletion of classes yet. 

It works for the (all methods) case because we use this feature of the Tooling API:

See https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/intro_rest_resources.htm

"Multiple occurrences of a test method name in a testMethods array are ignored. Test methods that don’t exist are skipped. **A null or missing testMethods array specifies that all test methods in the test class are run**."

An API for (all classes) is in the works. But, for now, when you add/delete classes you have to reconfigure the launch configuration.

**Comment by ImJohnMDaniel** [comment]
Hey @vazexqi, Yup, I get it.  Thanks for the clarification.
