### ISSUE TITLE
Question: What does "Add/Remove Jorje Builder" do?

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/idecore#172]
Hey @vazexqi and @gwestersfdc 

What does "Add/Remove Jorje Builder" do?  Seeing it in the new beta release from this week.

Thanks for the help.

Cheers!

**Comment by vazexqi** [comment]
It's a program analysis feature that we are building. It's going to scan/index all the Apex files in your workspace and build up a model for it. This model would then be used to enable things like code navigation, type hierarchy, smarter code completion, etc. It's called "Jorje Builder" because (i) Jorje is the name of the new apex compiler and "Builder" comes from Eclipse parlance to mean something that runs each time you save a file.

You have already seen bits of Jorje being used, e.g., in the outline view, for the systems completion, for determining test methods, etc. This Jorje Builder is our initiative to unify all of that into one central point.

For now, you should leave it turned off. Nothing has been hooked up to use it (yet) :-)

**Comment by ImJohnMDaniel** [comment]
Thanks for the info!
