### ISSUE TITLE
Make downloading of "Referenced Packages" optional to save project initialization time

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/idecore#187]
@vazexqi and @gwestersfdc 

Why does Force.com IDE need "Referenced Packages" folder??  

In larger orgs, when I setup a new project against a sandbox, I often find that I am waiting for sometime while the contents of this folder download. 

I know in my own projects, I immediately put an entry in the .gitignore file to exclude this folder. 

Is there really any use / purpose in having this folder??

Thanks for the info.

Cheers!

**Comment by ImJohnMDaniel** [comment]
As added context, I did a quick search and found this post

https://developer.salesforce.com/forums/?id=906F00000008kfmIAA

JonP (SFDC Product Manager back in 2009) makes the following comment: "It's there because there's no other mechanism available to request managed content, but some of the files may be useful for reference (but not for editing)."  -- In six years of working on SFDC development and utilizing the Force.com IDE (and other IDEs), I can honestly say that I have never looked in this folder and referenced any managed package file.

Is there another reason to have this folder beside the one that JonP mentioned?

**Comment by vazexqi** [comment]
@ImJohnMDaniel - Yes, you're right. This is mostly there for historical reasons.

There are several _future_ use cases for them though:

1. Symbol information so that if you are using extending or using any of the managed packages, you should be able to get auto-completion (not yet). This is not limited to Apex per-se but could be useful for Lightning as well to get the component definitions of things that you have installed and want to use.
1. ISV Debugging (new feature coming). If you are an ISV and you are debugging in your **subscriber** org, you should be able to download the source of the packages that you maintain so you can debug them via the Apex Debugger.

However, I agree that for most uses, downloading it is a waste and we should not download it by default. We might filter it out so that you only get the Apex, VisualForce and Lightning components automatically and nothing else.

**Comment by ImJohnMDaniel** [comment]
@vazexqi - Thanks for the info.

So, what makes sense going forward?  Does this issue need to be re-phrased as a true bug (...it was originally just intended to be a Question thread)?  Do I need to open a new enhancement request and close this one?

Any suggestions would be appreciated.

Cheers!

**Comment by vazexqi** [comment]
![screen shot 2016-07-22 at 9 22 05 am](https://cloud.githubusercontent.com/assets/54414/17063831/11b6f724-4fee-11e6-88e9-2338e8086aa9.png)

Just to add to this discussion. If your org has the Salesforce Connected apps packages (if you use OAuth with any of our products, it automatically installs them), you see those packages as well. While they don't take a long time to download, they do clutter up the reference folders and they don't provide any useful information.

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
