### ISSUE TITLE
Unable to run test suite

### ISSUE THREAD

**Issue by rherrmann** [forcedotcom/idecore#195]
Following the [Getting Started instructions](https://github.com/forcedotcom/idecore/wiki/Getting-Started), I was able to set up a worksapce. However, most test projects seem to have unresolved dependencies. Am I missing something here?

BTW, the project's README uses a complicated and misleading advice to get to the Getting Started page. How about a direct link?

**Comment by vazexqi** [comment]
@rherrmann - I need to update the instructions. I forgot to update them after we switched to Tycho.

In the mean time, since you seem to have gotten to the end (it seems that you only have test projects showing errors), there is just one more step you have to perform.

I'm not sure if this is because of a bug in Eclipse or the m2e connectors, but basically what happens is that they mess with the .classpath files in your locally cloned repo.

So, after installing the m2e connectors, go to your locally cloned repo and do a `git status`. Notice that there are entries in the .classpath that have been removed. Do a `git reset --hard` to restore them. I'll update the instructions soon and try to figure out the best way to handle the m2e connectors messing with the .classpath.

Fortunately, this weird step is only necessary when you set up a new workspace and install the m2e connectors.

**Comment by vazexqi** [comment]
I've updated the Getting Started guide.

To deal with the m2e connectors messing with .classpath issue, I've made it so that the instructions ask you to install the "Tycho Connector" first before importing the projects.

But, for developers who might have relied on the Quick Fix issue to install Tycho Connector after importing the projects, you can follow the steps above to do a `git status` and `git reset --hard` to resolve the issue.
