### ISSUE TITLE
Issue: Autocompletion

### ISSUE THREAD

**Issue by jandeschuttere** [forcedotcom/idecore#20]
Not sure if this is a general Eclipse issue or not (has been a while since I used eclipse for anything else but for the Force plugin) but when I'm adding/updating code, 7 out of 10 my code completion does not work. Have tried multiple reinstalls, tested on different computers.

**Comment by cnaccio** [comment]
Any update on this? Autocompletion is still not working for me in Eclipse 4.4, and Force.com IDE Plugin version 33. 

Thanks guys!

**Comment by vazexqi** [comment]
@cnaccio Did you try the beta version? System types (not user-defined types) are working.

As an approximation to user-defined types, I've been using Edit > Word Completion (invocable through Ctrl + .) in the current file.

See https://github.com/forcedotcom/idecore/wiki/Downloading-the-Beta-Version-of-the-Force.com-IDE
and https://github.com/forcedotcom/idecore/wiki/Changes-in-Force.com-IDE-Beta-Version-34.0.0.20150511

**Comment by smaypilot** [comment]
This is ridiculous that code completion is still not working.  I'm think about not pursuing Salesforce development because of the lack of this pretty much standard feature for any other programming language.  I have to go back to developing using the Salesforce Developer console to get code complete.  That's probably what Salesforce wants to "force" (pun intended) us to use.

**Comment by vazexqi** [comment]
Do you mean system completion or context-sensitive code completion (aka IntelliSense)? Context-sensitive code completion is pending the completion of our new Apex compiler. But system code completions does work as can be seen in this video. I _just_ recorded it. The video shows installation of a fresh Eclipse instance all the way to checking out a new project and editing it.

https://vimeo.com/169312794

Perhaps you can provide more details on what issues you are facing.

**Comment by smaypilot** [comment]
I’m getting neither.  Tried control-space on my mac and I get the following:



Thanks

Steve May

**Comment by smaypilot** [comment]
Which version of Java do you have installed. I’m running 

Not sure if that matters.

Steve

**Comment by vazexqi** [comment]
I can't see what you pasted or inline on GitHub. Could you use the web interface? I don't think the e-mail function embeds stuff.

I am running Java 8

```
nchen@nchen-wsm1:~|⇒  java -version                                                                                             17:15:28
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)

**Comment by KeithClarke** [comment]
@smaypilot Also consider switching to http://www.illuminatedcloud.com/ that includes http://www.illuminatedcloud.com/home/completion.

**Comment by smaypilot** [comment]
Looks like that would mean switching to intelij. We are way more comfortable with Eclipse and like to stick with that if possible.

Steve

**Comment by smaypilot** [comment]
RESOLUTION>  I can't believe what the solution to the issue was.  I tried the exact same version of Eclipse (i.e. Kepler) and same version of Force.com IDE but that still did no solve my issue.  I also noticed I kept on getting logon errors when attempting to open the salesforce.schema (i.e. schema browser).  I tried adding my token to the password and also in the token field when logging on.  That still did not seem to resolve it.

Turns out the issue was with my Eclipse's Secure Storage settings i.e. cached password.  I needed to go into Eclipse > Preferences > Security > Secure Storage and click "Clear Passwords".   Clearing the passwords seemed to have resolved the issue for me.

I go a clue that the Secure Storage may be the culprit after reading one of the error reports being sent to Eclipse:

https://dev.eclipse.org/recommenders/community/aeri/v2/#!/submissions/AIJBFzWLu6Yw5AGSEEa4iFUI4hw9uMwT8zL032l0iL01aTTz8kegufyL59H6ApwY

Very strange issue because it seems I was able to authenticate and load my Apex Classes/Visual Force files etc. yet it would not seem to authenticate when attempting to open the salesforce.schema and authentication also seems to be related to content assist feature.

I hope this helps others that I have heard are experiencing issues with loading the salesforce.schema file/browser or not getting content assist (i.e. System completion) to work.

**Comment by smaypilot** [comment]
When will Context-sensitive code completion as a result of the new Apex compiler be available? The current version 36 does not seem to support it but if I go back to version 30 it seems to still work.

**Comment by daveb-501commons** [comment]
I have Force IDE (BETA v36) installed in Eclipse (v4.6) on Windows 10 and the System. Auto Complete is working fine.  Above mention by @vazexqi Nick "Context-sensitive code completion is pending the completion of our new Apex compiler.".   To get autocomplete parity w/ Salesforce Editor and Developer Console for Apex related autocomplete pending new Apex compiler.  

Is there an ETA on the new Apex compiler?
Are you open for contributions/testing to help move it along?

**Comment by vazexqi** [comment]
The new compiler is far along now that we do get context sensitive code completion for Apex. 

All new features are being developed for our VS Code Extensions for Salesforce DX flow. Find out more at https://github.com/forcedotcom/salesforcedx-vscode/tree/develop/packages/salesforcedx-vscode-apex and how to get started using https://github.com/forcedotcom/salesforcedx-vscode/wiki

The code completion is being done in an IDE-agnostic way using http://langserver.org/ so it can work across multiple IDEs. However, our focus is on VS Code for Salesforce DX.
