### ISSUE TITLE
How to build a a deployable package?

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#206]
Forgive me if this is easy but how do I now build the foce.com plugin so that I can host my own version from an Eclipse IDE update site? It seems Maven's getting in a way for what's the standard way of doing it for Eclipse - https://wiki.eclipse.org/FAQ_How_do_I_create_an_update_site_(site.xml)%3F

I've tried a few of the built in targets, but with no success. Thank you kindly for any guidance you can provide on how I can build the plugin.

**Comment by danielsokolowski** [comment]
Pinging @vazexqi , any chance you can take 5 min to just provide some steps on how you build it yourself, it might be just enough for me to move forward.

**Comment by vazexqi** [comment]
@danielsokolowski - Just an ACK to let you know I'm reading this (and your other pull request) :-) 

We have an update site repository "plug-in" that is not part of this idecore repo. I'm trying to see what is the best way to move forward on that. Exposing that would not help because that has dependencies on other things (debugger, lightning) that are not open source. So, maybe it's best to create a different one for idecore that just does idecore.

**Comment by BlackH0l3** [comment]
yes, we really need a tutorial.

**Comment by vazexqi** [comment]
@danielsokolowski @BlackH0l3 - I just want to gather the requirements first before I implement something. 

Per my understanding, you want:
1) A way to build your own version of the Force.com plug-in (this is what we call a feature)
2) A way to build an update site for your own version of the Force.com plug-in (this is what we call a repository)
3) Some tutorial on how to use 1 and 2 above?

**Comment by BlackH0l3** [comment]
yes, absolutely right! we need 1,2, and 3.

very thanks.

**Comment by danielsokolowski** [comment]
Hi @vazexqi , I just need enough breadcrumbs to get past **1**, there is good info on the net on how to do **2** - if I figure it out I'll be happy to write a tutorial so that others can follow.

**Comment by vazexqi** [comment]
@danielsokolowski #1 is actually the hardest step since I need to create external versions of certain plug-ins/dependencies. I've just done that. The [Getting Started](https://github.com/forcedotcom/idecore/wiki/Getting-Started) has been updated. And I've also added a screencast to make the process clearer. The screencast is available at https://vimeo.com/191250875

Let me know if you need any other assistance. Else I'm going to close this issue as fixed.

**Comment by vazexqi** [comment]
Marking as fixed. Please file a new issue if you need more assistance on this.
